version: 2
jobs:
    build:
        docker:
            - image: circleci/node:14-stretch-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - run: yarn install

            # run tests!
            - run: yarn run lerna link
            - run: yarn run lint
            - run: yarn run build
            - run: yarn test
            - run: yarn run saucelabs
