version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.1.0-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn run lerna link
      - run: yarn run lint
      - run: yarn run build
      - run: yarn test
      - run: yarn run saucelabs
